[package]
name = "r7z"
version = "0.1.0"
edition = "2021"
license = "LGPL-2.1-or-later"
description = "Pure-Rust library for reading and writing .7z archives"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7"
smallvec = "1"
bytes = "1"
crc32fast = "1.5.0"
lzma-rust2 = { version = "0.16.2", features = ["encoder", "optimization"] }
memmap2 = "0.9"
nom = "8"
num = "0.4"
num-derive = "0.4"
num-traits = "0.2"
thiserror = "2"
aes = "0.8"
cbc = "0.1"
sha2 = "0.10"

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }
hex = "0.4"
tempfile = "3.26.0"
pprof = { version = "0.15", features = ["flamegraph"] }
xz2 = "0.1.7"

[[bench]]
name = "parse_bench"
harness = false

[[bench]]
name = "comparison"
harness = false

[profile.release]
debug = true
