#!/usr/bin/env bash
set -euo pipefail

root="$(git rev-parse --show-toplevel)"
cd "$root"
out="${R7Z_ORACLE_INVENTORY:-target/oracle-inventory}"
mkdir -p "$out"

p7zip_bin="$(scripts/ensure_p7zip_oracle.sh)"
official_bin="$(scripts/ensure_official_7zip.sh)"

describe() {
  local name="$1" bin="$2" source="$3" build="$4" invocation="$5"
  local resolved hash info methods
  resolved="$(realpath "$bin")"
  hash="$(sha256sum "$resolved" | cut -d ' ' -f 1)"
  info="$out/$name-info.txt"
  methods="$out/$name-methods.txt"
  "$resolved" i > "$info" 2>&1
  awk 'BEGIN { copy=0 } /^Formats:/ { copy=1 } /^Hashers:/ { exit } copy { print }' "$info" > "$methods"
  {
    printf '### %s\n\n' "$name"
    printf -- '- Version and executable identity: `'; awk 'NF { print; exit }' "$info" | tr '\n' ' '; printf '`\n'
    printf -- '- Executable: `%s`\n' "$resolved"
    printf -- '- SHA-256: `%s`\n' "$hash"
    printf -- '- Source: %s\n' "$source"
    printf -- '- Build: %s\n' "$build"
    printf -- '- Inventory invocation: `%s i`\n' "$resolved"
    printf -- '- Compatibility invocation: `%s`\n' "$invocation"
    printf -- '- Formats and methods: [`%s`](%s)\n\n' "$(basename "$methods")" "$(basename "$methods")"
  } >> "$out/README.md"
}

: > "$out/README.md"
printf '# 7z oracle inventory\n\nGenerated by `scripts/record_7z_oracles.sh`. Compatibility tests select the p7zip executable with `P7ZIP_BIN`; `tests/support/mod.rs` logs its canonical path, SHA-256, and version on first use in each test process.\n\n' >> "$out/README.md"

describe \
  p7zip \
  "$p7zip_bin" \
  'p7zip-project/p7zip commit `6819e2dc1917e1267babddc6391cea56ead7123d`' \
  'GCC Makefile defaults via `make -C CPP/7zip/Bundles/Alone2 -f makefile.gcc`' \
  "P7ZIP_BIN=$p7zip_bin devenv shell -- cargo test --test interop_test --test interop_write_test --test corpus_test -- --nocapture"

describe \
  official-7zip \
  "$official_bin" \
  'official 7-Zip Linux x64 release 26.03; archive SHA-256 is checked by `ensure_official_7zip.sh`' \
  'official release build' \
  "$PWD/$official_bin l -slt archive.7z; $PWD/$official_bin t archive.7z"

printf '### In-process liblzma test backend\n\n- Rust binding: `xz2 %s` (`lzma-sys %s`, from Cargo.lock)\n- Invocation: `devenv shell -- cargo test --test lzma_perf_test -- --ignored --nocapture`\n- Used for codec performance comparisons in `tests/lzma_perf_test.rs`; it is not an archive CLI oracle.\n' \
  "$(awk '/^name = "xz2"$/{found=1;next} found && /^version = /{gsub(/"/, "", $3); print $3; exit}' Cargo.lock)" \
  "$(awk '/^name = "lzma-sys"$/{found=1;next} found && /^version = /{gsub(/"/, "", $3); print $3; exit}' Cargo.lock)" >> "$out/README.md"

printf '%s\n' "$out/README.md"
